interface CardsData {
  link: string,
  enLink: string,
  heading: string,
  enHeading: string,
  text: string,
  enText: string,
  img: string,
  alt: string,
  enAlt: string,
  iconCls: string,
}

export const aboutUsCardData: CardsData[] = [
  {
    link: "/about-us/message",
    enLink: "/about-us/message/en",
    heading: "代表者メッセージ",
    enHeading: "Message",
    text: "活動の中心であり、代表のマンフィーのご挨拶を記載しております。",
    enText: "It is the center of the activity, and the greeting of the representative Manfi is drawn.",
    img: "/images/top/representative.jpg",
    alt: "",
    enAlt: "",
    iconCls: "message",
  },
  {
    link: "/about-us/overview",
    enLink: "/about-us/overview/en",
    heading: "なぜ活動をするのか。目標。",
    enHeading: "Why do you work? the goal.",
    text: "活動のきっかけは？活動目標についてなど、マンフィーの経験などからご紹介します。",
    enText: "What made you want to do this? Introducing from Monpfy's experience, such as activity goals.",
    img: "/images/top/group-overview.jpg",
    alt: "",
    enAlt: "",
    iconCls: "staff",
  },
  {
    link: "/about-us/report",
    enLink: "/about-us/report/en",
    heading: "年次会計報告",
    enHeading: "Accounting report",
    text: "2020年以降の会計記録を掲載させていただいてます。",
    enText: "Accounting records from 2020 to 2022 are posted.",
    img: "/images/top/relief-supplies.jpg",
    alt: "",
    enAlt: "",
    iconCls: "note",
  }
]

export const projectCardData: CardsData[] = [
  {
    link: "/project/school-construction/",
    enLink: "/project/school-construction/en",
    heading: "学校建設",
    enHeading: "School Construction",
    text: "2016年9月20日悲願だったガーナへの学校設立が現実になりました。",
    enText: "September 20, 2016 The school started operations in Ghana.",
    img: "/images/top/school-construction.jpg",
    alt: "",
    enAlt: "",
    iconCls: "school",
  },
  {
    link: "/project/bore-hole-construction",
    enLink: "/project/bore-hole-construction/en",
    heading: "なぜ活動をするのか。目標。",
    enHeading: "Well construction",
    text: "活動のきっかけは？活動目標についてなど、マンフィーの経験などからご紹介します。",
    enText: "By building a well, we can see the future of our children.",
    img: "/images/top/well-construction.jpg",
    alt: "",
    enAlt: "",
    iconCls: "well",
  },
  {
    link: "/project/supplies-support",
    enLink: "/project/supplies-support/en/",
    heading: "支援物資提供",
    enHeading: "Relief Supplies",
    text: "衣類、文房具など。貧しい家庭では何もかも重宝しています。",
    enText: "Clothing, stationery, etc. Everything comes in handy in poor families.",
    img: "/images/top/relief-supplies.jpg",
    alt: "",
    enAlt: "",
    iconCls: "note",
  },
  {
    link: "/project/fundraising",
    enLink: "/project/fundraising/en",
    heading: "募金活動",
    enHeading: "Fundraising Activities",
    text: "全ての方々の支えで多くのことが現実にできています。",
    enText: "Many things are actually done with the support of all people.",
    img: "/images/top/donate.jpg",
    alt: "",
    enAlt: "",
    iconCls: "donate",
  }
]
